#!/bin/bash
set -e

mkdir -p /build/app/usr
USE_X11=${USE_X11:+1}
[ -n "${USE_X11}" ] && \
  apt install -y libx11-dev && \
  echo ", libx11-6" >> /build/dependencies/INSTALLwhi

git clone -b "${BRANCH:=master}" "${REPOSITORY:?Repository is not defined.}" /src
pushd /src   >/dev/null
  cmake -DCMAKE_INSTALL_PREFIX=/build/app/usr \
    -DNO_MARCH_NATIVE=ON .
  make install
popd         >/dev/null

pushd /build >/dev/null
  mkdir -p out

  if [[ "${BRANCH}" =~ ^v ]]; then
    echo "${BRANCH}" | sed -E 's|v||' > /build/APP_VERSION
  else
    grep -F '#define VERSION' /src/uxplay.cpp | \
      awk '{print $3}' | \
      sed 's|"||g' \
      > /build/APP_VERSION
  fi
  echo $(cat /build/APP_VERSION)+${PKG_MAINTAINER_VERSION:=rf49}-${PKG_REVISION_NUMBER:-1} > /build/PKG_VERSION
popd         >/dev/null

pushd /build/app >/dev/null
  [ -d DEBIAN ] && rm -rf DEBIAN || :
  mkdir -p DEBIAN
  cd DEBIAN
  echo "Package: " ${PKG_NAME:?'Package name not defined.'} >> control
  echo "Version: " $(cat /build/PKG_VERSION)                >> control
  echo "Architecture: " \
    $(dpkg-architecture -q DEB_HOST_ARCH)                   >> control
  echo "Maintainer: " "${PKG_MAINTAINER}"                   >> control
  echo "Depends: " \
    $(cat /build/dependencies/INSTALL)                      >> control
  [ -n "${PKG_SECTION}" ] && \
    echo "Section: " ${PKG_SECTION}                         >> control
  [ -n "${PKG_PRIORITY}" ] && \
    echo "Priority: " ${PKG_PRIORITY}                       >> control
  echo "Homepage: " "${REPOSITORY}"                         >> control
  echo "Description: " \
    "${PKG_DESCRIPTION:-No description provided.}"          >> control
popd             >/dev/null

pushd /build >/dev/null
  dpkg-deb --root-owner-group --build app \
    out/"${PKG_NAME}_$(cat /build/PKG_VERSION)_$(dpkg-architecture -q DEB_HOST_ARCH).deb"
popd         >/dev/null
